#!/bin/bash
#PBS -l nodes=1:ppn=8:dc2,walltime=0:05:00
#PBS -N checkOrientation
#PBS -V

if [ $ENV == "IUHPC" ]; then
   module load fsl
fi


export input_nii=`$(jq -r '.input' config.json)`

export orientation=`$(fslorient $input_nii)`

echo $orientation

cat <<EOF > product.json
{"orientation" : "$orientation"}
EOF
