#!/bin/bash
#PBS -l nodes=1:ppn=8:dc2,walltime=0:05:00
#PBS -N checkOrientation
#PBS -V

if [ $ENV == "IUHPC" ]; then
   module load fsl
fi

dtiinit=`$SERVICE_DIR/jq -r '.dtiinit' config.json`
export input_nii=$dtiinit/`$SERVICE_DIR/jq -r '.files.alignedDwRaw' $dtiinit/dt6.json`


export orientation=`fslorient $input_nii`

echo $orientation

cat <<EOF > product.json
{"orientation" : "$orientation"}
EOF
